---
- name: config_samba | configuring samba
  template:
    src: "{{ item.template }}.j2"
    dest: "/{{ item.name }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - restart samba
  with_items:
    - template: etc/krb5.conf
      name: 'etc/krb5.conf'
    - template: etc/samba/smb.conf
      name: 'usr/local/etc/smb4.conf'

- name: config_samba | checking if domain created
  stat:
    path: "/var/log/.samba_ad_created"
  register: samba_ad_created_check

- name: config_samba | configuring Active Directory
  shell: "samba-tool domain provision --realm={{ samba_ad_info['kerberos_realm']|upper }} --domain={{ samba_ad_info['netbios_domain_name']|upper }} --adminpass='{{ samba_ad_info['adminpass'] }}' --server-role='domain controller' --use-ntvfs"
  register: samba_ad_created
  when: >
        not samba_ad_created_check['stat']['exists'] and
        (samba_create_domain_controller is defined and
          samba_create_domain_controller) and
        samba_server_role == "active directory domain controller"

- name: config_samba | marking domain as created
  file:
    dest: "/var/log/.samba_ad_created"
    state: touch
  when: >
        samba_ad_created['changed'] and
        not samba_ad_created_check['stat']['exists']
