---
- name: config_samba | configuring samba
  template:
    src: "{{ item.template }}"
    dest: "{{ item.name }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - restart samba
  with_items:
    - template: krb5.conf.j2
      name: /etc/krb5.conf
    - template: smb.conf.j2
      name: /usr/local/etc/smb4.conf
