---
# tasks file for ansible-samba
- name: Install samba
  pkgng: name=samba46 state=present

- name: Enable samba
  sysrc: name=samba_server_enable value="YES"

- include: create_ad.yml
  when: samba_create_domain_controller

#
#- include: samba_groups.yml
#
#- include: samba_users.yml
#
#- include: create_shares.yml

- name: Start samba
  service: name=samba_server state=started


- include: domain_users.yml
